-- MySQL Script generated by MySQL Workbench
-- Thu Aug  8 02:49:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `user_email` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_date` DATETIME NOT NULL,
  `user_phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`endereco` (
  `end_id` INT NOT NULL AUTO_INCREMENT,
  `end_rua` VARCHAR(120) NOT NULL,
  `end_numero` INT NOT NULL,
  `end_complemento` VARCHAR(60) NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end_cidade_uf` VARCHAR(45) NOT NULL,
  `end_cep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`end_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`endereco_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`endereco_users` (
  `endereco_end_id` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`endereco_end_id`, `users_user_id`),
  INDEX `fk_endereco_has_users_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_endereco_has_users_endereco1_idx` (`endereco_end_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_has_users_endereco1`
    FOREIGN KEY (`endereco_end_id`)
    REFERENCES `pizzaria`.`endereco` (`end_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_has_users_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `pizzaria`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`produtos` (
  `produto_id` INT NOT NULL AUTO_INCREMENT,
  `produto_name` VARCHAR(80) NOT NULL,
  `produto_desc` VARCHAR(255) NOT NULL,
  `produto_valor` DECIMAL(10,2) NOT NULL,
  `produto_tipo` VARCHAR(45) NOT NULL,
  `produto_categoria` VARCHAR(60) NOT NULL,
  `produto_status` TINYINT NOT NULL,
  PRIMARY KEY (`produto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`venda` (
  `venda_id` INT NOT NULL AUTO_INCREMENT,
  `venda_user_id` INT NOT NULL,
  `venda_produto_id` INT NOT NULL,
  `venda_endereco_id` INT NOT NULL,
  `venda_num_pedido` INT NOT NULL,
  `venda_quantidade` INT NOT NULL,
  `venda_valor_total` DECIMAL(10,2) NOT NULL,
  `venda_pagamento` VARCHAR(30) NOT NULL,
  `venda_data` DATETIME NOT NULL,
  PRIMARY KEY (`venda_id`),
  INDEX `fk_venda_users1_idx` (`venda_user_id` ASC) VISIBLE,
  INDEX `fk_venda_produtos1_idx` (`venda_produto_id` ASC) VISIBLE,
  INDEX `fk_venda_endereco1_idx` (`venda_endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_users1`
    FOREIGN KEY (`venda_user_id`)
    REFERENCES `pizzaria`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produtos1`
    FOREIGN KEY (`venda_produto_id`)
    REFERENCES `pizzaria`.`produtos` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_endereco1`
    FOREIGN KEY (`venda_endereco_id`)
    REFERENCES `pizzaria`.`endereco` (`end_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`admin_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`admin_users` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(100) NOT NULL,
  `admin_email` VARCHAR(100) NOT NULL,
  `admin_password` VARCHAR(255) NOT NULL,
  `admin_date` DATETIME NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
