DROP DATABASE IF EXISTS login_system;

CREATE DATABASE login_system;

USE login_system;

CREATE TABLE users(
user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome_user VARCHAR(100) NOT NULL,
email_user VARCHAR(120) NOT NULL,
user_password VARCHAR(255) NOT NULL
);